name: Generate README from Manifest

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run README generation script
        run: |
          python .github/scripts/readme-generate.py --json ./manifest.json --output ./README.md

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes directly to master
        run: |
          # Add and commit README.md if there are changes
          git add README.md
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "[Automated] Human Readable Manifest Update"
            git push origin master
          fi

      - name: Update RoveComm_CPP
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.RC_PAT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/MissouriMRDT/RoveComm_CPP/dispatches \
          -d '{"event_type":"rovecomm_sync", "client_payload":{}}'
